In [1]:
from torchvision import datasets

In [2]:
data_path = '../../.data/'

In [3]:
cifar10_train = datasets.CIFAR10(data_path, train=True, download=True)

URLError: <urlopen error [Errno 8] nodename nor servname provided, or not known>

In [ ]:
cifar10_val = datasets.CIFAR10(data_path, train=False, download=True)

We need to  implement two methods in dataset: __len__, __gettem__

In [ ]:
# if __len__ is emplemented:
len(cifar10_train)

In [4]:
img, label = cifar10[99]
img, label

NameError: name 'cifar10' is not defined

In [6]:
import matplotlib.pyplot as plt

In [ ]:
plt.imshow(img)
plt.show()

In [7]:
from torchvision import transforms
dir(transforms)

['AugMix',
 'AutoAugment',
 'AutoAugmentPolicy',
 'CenterCrop',
 'ColorJitter',
 'Compose',
 'ConvertImageDtype',
 'ElasticTransform',
 'FiveCrop',
 'GaussianBlur',
 'Grayscale',
 'InterpolationMode',
 'Lambda',
 'LinearTransformation',
 'Normalize',
 'PILToTensor',
 'Pad',
 'RandAugment',
 'RandomAdjustSharpness',
 'RandomAffine',
 'RandomApply',
 'RandomAutocontrast',
 'RandomChoice',
 'RandomCrop',
 'RandomEqualize',
 'RandomErasing',
 'RandomGrayscale',
 'RandomHorizontalFlip',
 'RandomInvert',
 'RandomOrder',
 'RandomPerspective',
 'RandomPosterize',
 'RandomResizedCrop',
 'RandomRotation',
 'RandomSolarize',
 'RandomVerticalFlip',
 'Resize',
 'TenCrop',
 'ToPILImage',
 'ToTensor',
 'TrivialAugmentWide',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_pil_constants',
 '_presets',
 'autoaugment',
 'functional',
 'functional_pil',
 'functional_tensor',
 'transforms']

In [9]:
to_tensor = transforms.ToTensor()

In [ ]:
img_t = to_tensor(img)
img_t.shape

In [ ]:
tensor_cifar10 = datasets.CIFAR10(data_path, 
                                  train=True, 
                                  download=False, 
                                  transform=transforms.ToTensor()
                                 )

img_t, _ = tensor_cifar10[99]
type(img_t)

In [ ]:
img_t.shape, img_t.dtype

In [ ]:
img_t.min(), img_t.max()

In [ ]:
# verify if tensor produced the same picture
plt.imshow(img_t.permute(2, 0, 1))
plt.show()

In [10]:
print('help')

help


### Calculating normalization requiers calculating mean and std of the entire dataset. 
Do do so we calculate it offline and we will use those values in tarnsform 

In [11]:
import torch

In [ ]:
imgs = torch.stack([img_t for img_t in tensor_cifar10], dim=3)
imgs.shape

In [ ]:
mean = imgs.view(3, -1).mean(dim=1)

In [ ]:
std = imgs.view(3, -1).std(dim=1)

In [ ]:
transformed_cifar10 = datasets.CIFAR10(root=data_path,
                                       train=True,
                                       download=True,
                                       transform=transforms.Compose([
                                           transforms.ToTensor(),
                                           transforms.Normalize(mean=mean, 
                                                                std=std)])
                                      )

## Choose only two labels out of ten
and remap remaining so they are contiguos

In [12]:
label_map = {0: 0, 2: 1}

In [ ]:
class_names = ['airplane', 'bird']
cifar2_train = [(img, label) for img, label in cifar10_train if label in [0, 2]]
cifar2_val = [(img, label) for img, label in cifar10_val if label in [0, 2]]

In [ ]:
# HOMEWORK: Implement proper Dataset class. 
# Above is just shortcut because it implements nativily basic properties __len__ and __getitem__ as this is
# a python list

## Basic fully connected model

In [13]:
import torch.nn as nn

In [14]:
n_out = 2

In [15]:
model = nn.Sequential(
    nn.Linear(3072,
              512),
    nn.Tanh(),
    nn.Linear(512,
              n_out),
    nn.Softmax(dim=1) # because usually vectors of pictures come in batches so will be 2D
    )

### Test weights vs output channels

In [26]:
#input_ = torch.randint(0, 3, size=(1, 3, 6, 6))
input_ = torch.rand(size=(1, 3, 6, 6))

In [76]:
input_

tensor([[[[0.2814, 0.3236, 0.5251, 0.8745, 0.2075, 0.6007],
          [0.5905, 0.3650, 0.9616, 0.2075, 0.2012, 0.7725],
          [0.2678, 0.1341, 0.2633, 0.5301, 0.7616, 0.3481],
          [0.3577, 0.8943, 0.0035, 0.2745, 0.2316, 0.7441],
          [0.3325, 0.1168, 0.6577, 0.6795, 0.7660, 0.9471],
          [0.5725, 0.7313, 0.1720, 0.8884, 0.2323, 0.5187]],

         [[0.6268, 0.3209, 0.9148, 0.3240, 0.2251, 0.5817],
          [0.7524, 0.7348, 0.2570, 0.7739, 0.9617, 0.3399],
          [0.7916, 0.5557, 0.9320, 0.5991, 0.3585, 0.0904],
          [0.1091, 0.1055, 0.5689, 0.6580, 0.6072, 0.0571],
          [0.1646, 0.2662, 0.3001, 0.4047, 0.0210, 0.5165],
          [0.5935, 0.7619, 0.5958, 0.2795, 0.7960, 0.3057]],

         [[0.5799, 0.0037, 0.7455, 0.0312, 0.0270, 0.1203],
          [0.1000, 0.2781, 0.8365, 0.2436, 0.1266, 0.4730],
          [0.4981, 0.5390, 0.2666, 0.0941, 0.1562, 0.5990],
          [0.5762, 0.5115, 0.6334, 0.9389, 0.6829, 0.6668],
          [0.4654, 0.8753, 0.6867, 0

In [77]:
conv = nn.Conv2d(in_channels=3, out_channels=1, kernel_size=3, padding=0)

In [78]:
with torch.no_grad():
    conv.bias.zero_()

In [79]:
conv.bias

Parameter containing:
tensor([0.], requires_grad=True)

In [89]:
input0_00 = input_[0][0, :3, :3]
input0_00

tensor([[0.2814, 0.3236, 0.5251],
        [0.5905, 0.3650, 0.9616],
        [0.2678, 0.1341, 0.2633]])

In [90]:
input1_00 = input_[0][1, :3, :3]
input1_00

tensor([[0.6268, 0.3209, 0.9148],
        [0.7524, 0.7348, 0.2570],
        [0.7916, 0.5557, 0.9320]])

In [91]:
input2_00 = input_[0][2, :3, :3]
input2_00

tensor([[0.5799, 0.0037, 0.7455],
        [0.1000, 0.2781, 0.8365],
        [0.4981, 0.5390, 0.2666]])

In [82]:
conv.weight.shape, conv.weight

(torch.Size([1, 3, 3, 3]),
 Parameter containing:
 tensor([[[[ 0.1112,  0.1618, -0.1609],
           [ 0.0354, -0.1405, -0.0237],
           [ 0.0952, -0.1378,  0.1907]],
 
          [[-0.1761,  0.0195, -0.1216],
           [-0.0506,  0.0043, -0.0968],
           [ 0.0602, -0.0994, -0.1581]],
 
          [[ 0.0703,  0.0795, -0.1921],
           [ 0.1512,  0.0201,  0.0954],
           [-0.0036, -0.0489, -0.0346]]]], requires_grad=True))

In [99]:
ch1_sum = (conv.weight[0][0] * input0_00).sum()

In [100]:
ch2_sum = (conv.weight[0][1] * input1_00).sum()

In [101]:
ch3_sum = (conv.weight[0][2] * input2_00).sum()

In [102]:
ch1_sum + ch2_sum + ch3_sum

tensor(-0.4657, grad_fn=<AddBackward0>)

In [86]:
with torch.no_grad():
    output = conv(input_)
output 

tensor([[[[-0.4657, -0.2947,  0.1012, -0.1612],
          [-0.5741, -0.1299, -0.2826, -0.3040],
          [-0.2127, -0.0852, -0.1258,  0.0702],
          [-0.0200,  0.0420, -0.2817, -0.1395]]]])